name: Test on Multiple Linux Distributions

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, master]


jobs:
  test-on-multiple-distros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [archlinux, fedora, debian, leplusorg/kali]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests on ${{ matrix.distro }}
        run: |
          docker run --rm ${{ matrix.distro }} sh -c "
            apt-get update && apt-get install -y wget gtk3|| \
            dnf install -y wget gtk3 || \
            pacman -Sy --noconfirm wget gtk3 || \
            wget https://github.com/pop-ecx/zfetch/releases/download/v0.3.0/zfetch
            chmod +x zfetch
            ./zfetch
          "
