name: Test zfetch on Multiple Linux Distributions

on:
  push:
    branches: [dev]
  pull_request:
    branches: [master]

jobs:
  test-zfetch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [archlinux, fedora]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test zfetch on ${{ matrix.distro }}
        run: |
          if [ '${{ matrix.distro }}' = 'archlinux' ]; then
            docker run --rm archlinux sh -c "
              pacman -Sy --noconfirm gtk3 wget coreutils
              wget https://github.com/pop-ecx/zfetch/releases/download/v0.3.0/zfetch
              chmod +x zfetch
              ./zfetch
            "
          elif [ '${{ matrix.distro }}' = 'fedora' ]; then
            docker run --rm fedora sh -c "
              dnf install -y gtk3 tar wget coreutils redhat-lsb-core hostname
              wget https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz
              tar -xf zig-linux-x86_64-0.11.0.tar.xz
              echo $PWD
            "
          fi
